export const HOTEL_DATA = {
  "countryGroups": [
    {
      "countryCode": "DE",
      "countryName": "GERMANY",
      "items": [
        {
          "domainRefID": "POT",
          "domainName": "Potsdam",
          "hotelRefID": "PROT",
          "timeZoneCode": "DE",
          "cultureCode": "de-DE",
          "currencyCode": "EUR",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Potsdam",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 0,
          "leaseStartFirstDateOfMonth": 1,
          "fixedLeaseMonth": 5,
          "minLeaseMonth": 0,
          "alwayFullMonth": 1
        },
        {
          "domainRefID": "LEI",
          "domainName": "Leipzig",
          "hotelRefID": "LEI",
          "timeZoneCode": "DE",
          "cultureCode": "de-DE",
          "currencyCode": "EUR",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Leipzig",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 0,
          "leaseStartFirstDateOfMonth": 1,
          "fixedLeaseMonth": 5,
          "minLeaseMonth": 0,
          "alwayFullMonth": 1
        },
        {
          "domainRefID": "DTM",
          "domainName": "Dortmund",
          "hotelRefID": "DTM",
          "timeZoneCode": "DE",
          "cultureCode": "de-DE",
          "currencyCode": "EUR",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Dortmund",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 0,
          "leaseStartFirstDateOfMonth": 1,
          "fixedLeaseMonth": 5,
          "minLeaseMonth": 0,
          "alwayFullMonth": 1
        }
      ]
    },
    {
      "countryCode": "PL",
      "countryName": "POLAND",
      "items": [
        {
          "domainRefID": "LDZ1",
          "domainName": "Łódź Rewolucji",
          "hotelRefID": "LDZ1",
          "timeZoneCode": "PL",
          "cultureCode": "pl-PL",
          "currencyCode": "PLN",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Łódź Rewolucji",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 0,
          "leaseStartFirstDateOfMonth": 1,
          "fixedLeaseMonth": 0,
          "minLeaseMonth": 5,
          "alwayFullMonth": 1
        },
        {
          "domainRefID": "LDZ2",
          "domainName": "Łódź Rembielińskiego",
          "hotelRefID": "LDZ2",
          "timeZoneCode": "PL",
          "cultureCode": "pl-PL",
          "currencyCode": "PLN",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Łódź Rembielińskiego",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 0,
          "leaseStartFirstDateOfMonth": 1,
          "fixedLeaseMonth": 0,
          "minLeaseMonth": 5,
          "alwayFullMonth": 1
        },
        {
          "domainRefID": "KAT",
          "domainName": "Katowice",
          "hotelRefID": "KAT",
          "timeZoneCode": "PL",
          "cultureCode": "pl-PL",
          "currencyCode": "PLN",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Katowice",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 0,
          "leaseStartFirstDateOfMonth": 1,
          "fixedLeaseMonth": 0,
          "minLeaseMonth": 5,
          "alwayFullMonth": 1
        },
        {
          "domainRefID": "WRO",
          "domainName": "Wroclaw",
          "hotelRefID": "WRO",
          "timeZoneCode": "PL",
          "cultureCode": "pl-PL",
          "currencyCode": "PLN",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Wroclaw",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 0,
          "leaseStartFirstDateOfMonth": 1,
          "fixedLeaseMonth": 0,
          "minLeaseMonth": 5,
          "alwayFullMonth": 1
        }
      ]
    },
    {
      "countryCode": "DK",
      "countryName": "DENMARK",
      "items": [
        {
          "domainRefID": "CPH1",
          "domainName": "Sølvgade",
          "hotelRefID": "CPH1",
          "timeZoneCode": "DK",
          "cultureCode": "da-DK",
          "currencyCode": "DKK",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Copenhagen City",
          "isOpenEndedContract": true,
          "totalMonthsOpenEndedContract": 12,
          "leaseStartFirstDateOfMonth": 0,
          "fixedLeaseMonth": 0,
          "minLeaseMonth": 0,
          "alwayFullMonth": 0
        },
        {
          "domainRefID": "CPH2",
          "domainName": "Lyngby",
          "hotelRefID": "CPH2",
          "timeZoneCode": "DK",
          "cultureCode": "da-DK",
          "currencyCode": "DKK",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "Lyngby",
          "isOpenEndedContract": false,
          "totalMonthsOpenEndedContract": 12,
          "leaseStartFirstDateOfMonth": 0,
          "fixedLeaseMonth": 0,
          "minLeaseMonth": 0,
          "alwayFullMonth": 0
        },
        {
          "domainRefID": "CPH3",
          "domainName": "South Campus",
          "hotelRefID": "CPH3",
          "timeZoneCode": "DK",
          "cultureCode": "da-DK",
          "currencyCode": "DKK",
          "currencyDecimalDigits": 2,
          "currencyRoudingType": "RoundUp",
          "hotelName": "South Campus",
          "isOpenEndedContract": true,
          "totalMonthsOpenEndedContract": 12,
          "leaseStartFirstDateOfMonth": 0,
          "fixedLeaseMonth": 0,
          "minLeaseMonth": 0,
          "alwayFullMonth": 0
        }
      ]
    }
  ],
  "success": true,
  "errors": [],
  "warnings": []
}