/* This file is autogenerated from table {table_name}. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : DataServiceObjects.cst
 * Generator        : CodeSmith 8.0.15459 
 * Date             : 19-Apr-2023 05:02
 */
 
using System;

namespace XHS.DataServiceObjects
{
    [Serializable]
    public class {class_name}
    {
			{properties}
			public RPMAdminUser CreatedByUser;
			public RPMAdminUser UpdatedByUser;
    }
}
