/* This file is autogenerated from table Hotel_Booking_Extension_Template. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : Structure.cst
 * Generator        : CodeSmith 8.0.15459 
 * Date             : 19-Apr-2023 05:02
 */
 
using System;

namespace XHS.DataAccess
{
    public class Hotel_Booking_Extension_Templates
    {
        public Hotel_Booking_Extension_Template[] Collection;
    }

    public class Hotel_Booking_Extension_Template
    {
		public int ID;
		public int Hotel_ID;
		public int Hotel_Room_Type_ID;
		public int Hotel_Room_ID;
		public string Room_Confirmation_Number;
		public int Profile_ID;
		public string Code;
		public string Name;
		public string Description;
		public DateTime Effective_From;
		public DateTime Effective_To;
		public Boolean Skip_Admin_Fee_Policy;
		public int Extension_Notice_Period;
		public int Extension_Notice_Period_Type;
		public int Default_Extension_Term;
		public int Default_Extension_Term_Type;
		public DateTime Create_DateTime;
		public DateTime Update_DateTime;
        public User_AccountInfo CreatedByUser;
        public User_AccountInfo UpdatedByUser;
    }
}
