/* This file is autogenerated from table Hotel_Booking_Extension_Template. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : DSH_MakeDB_FromDSO.cst
 * Generator        : CodeSmith 8.0.15459 
 * Date             : 19-Apr-2023 05:02
 */
 
using System;

namespace XHS.DataServiceHelper
{
    public Hotel_Booking_Extension_Template MakeDB_HotelBookingExtensionTemplate(HotelBookingExtensionTemplate dsHotelBookingExtensionTemplate)
    {
        XHS.DataAccess.Hotel_Booking_Extension_Template dbHotelBookingExtensionTemplate = new XHS.DataAccess.Hotel_Booking_Extension_Template();
        
        dbHotelBookingExtensionTemplate.ID = dsHotelBookingExtensionTemplate.ID;
        dbHotelBookingExtensionTemplate.Hotel_ID = dsHotelBookingExtensionTemplate.HotelID;
        dbHotelBookingExtensionTemplate.Hotel_Room_Type_ID = dsHotelBookingExtensionTemplate.HotelRoomTypeID;
        dbHotelBookingExtensionTemplate.Hotel_Room_ID = dsHotelBookingExtensionTemplate.HotelRoomID;
        dbHotelBookingExtensionTemplate.Room_Confirmation_Number = this.NoNull(dsHotelBookingExtensionTemplate.RoomConfirmationNumber);
        dbHotelBookingExtensionTemplate.Profile_ID = dsHotelBookingExtensionTemplate.ProfileID;
        dbHotelBookingExtensionTemplate.Code = this.NoNull(dsHotelBookingExtensionTemplate.Code);
        dbHotelBookingExtensionTemplate.Name = this.NoNull(dsHotelBookingExtensionTemplate.Name);
        dbHotelBookingExtensionTemplate.Description = this.NoNull(dsHotelBookingExtensionTemplate.Description);
        dbHotelBookingExtensionTemplate.Effective_From = DateTimeHelper.FixDefaultValue(dsHotelBookingExtensionTemplate.EffectiveFrom);
        dbHotelBookingExtensionTemplate.Effective_To = DateTimeHelper.FixDefaultValue(dsHotelBookingExtensionTemplate.EffectiveTo);
        dbHotelBookingExtensionTemplate.Skip_Admin_Fee_Policy = dsHotelBookingExtensionTemplate.SkipAdminFeePolicy;
        dbHotelBookingExtensionTemplate.Extension_Notice_Period = dsHotelBookingExtensionTemplate.ExtensionNoticePeriod;
        dbHotelBookingExtensionTemplate.Extension_Notice_Period_Type = dsHotelBookingExtensionTemplate.ExtensionNoticePeriodType;
        dbHotelBookingExtensionTemplate.Default_Extension_Term = dsHotelBookingExtensionTemplate.DefaultExtensionTerm;
        dbHotelBookingExtensionTemplate.Default_Extension_Term_Type = dsHotelBookingExtensionTemplate.DefaultExtensionTermType;

        if (dsHotelBookingExtensionTemplate.CreatedByUser != null && dsHotelBookingExtensionTemplate.CreatedByUser.UserAccountID > 0)
        {
            dbHotelBookingExtensionTemplate.CreatedByUser = new User_AccountInfo { ID = dsHotelBookingExtensionTemplate.CreatedByUser.UserAccountID };
        }
        if (dsHotelBookingExtensionTemplate.UpdatedByUser != null && dsHotelBookingExtensionTemplate.UpdatedByUser.UserAccountID > 0)
        {
            dbHotelBookingExtensionTemplate.UpdatedByUser = new User_AccountInfo { ID = dsHotelBookingExtensionTemplate.UpdatedByUser.UserAccountID };
        }

        return dbHotelBookingExtensionTemplate;
    }
}
