/* This file is autogenerated from table Hotel_Booking_Extension_Template. Any modification will 
 * be lost once it is regenerated.
 *
 * Template         : DSC_MakeDSO_FromDBObject.cst
 * Generator        : CodeSmith 8.0.15459 
 * Date             : 19-Apr-2023 05:02
 */
 
using System;

namespace XHS.DataServiceConversions
{
    public XHS.DataServicesObjects.HotelBookingExtensionTemplate MakeDSO_HotelBookingExtensionTemplate(XHS.DataAccess.Hotel_Booking_Extension_Template dbHotelBookingExtensionTemplate)
    {
        if (dbHotelBookingExtensionTemplate == null) return null;

        XHS.DataServicesObjects.HotelBookingExtensionTemplate dsHotelBookingExtensionTemplate = new XHS.DataServicesObjects.HotelBookingExtensionTemplate();
        
        dsHotelBookingExtensionTemplate.ID = dbHotelBookingExtensionTemplate.ID;
        dsHotelBookingExtensionTemplate.HotelID = dbHotelBookingExtensionTemplate.Hotel_ID;
        dsHotelBookingExtensionTemplate.HotelRoomTypeID = dbHotelBookingExtensionTemplate.Hotel_Room_Type_ID;
        dsHotelBookingExtensionTemplate.HotelRoomID = dbHotelBookingExtensionTemplate.Hotel_Room_ID;
        dsHotelBookingExtensionTemplate.RoomConfirmationNumber = dbHotelBookingExtensionTemplate.Room_Confirmation_Number;
        dsHotelBookingExtensionTemplate.ProfileID = dbHotelBookingExtensionTemplate.Profile_ID;
        dsHotelBookingExtensionTemplate.Code = dbHotelBookingExtensionTemplate.Code;
        dsHotelBookingExtensionTemplate.Name = dbHotelBookingExtensionTemplate.Name;
        dsHotelBookingExtensionTemplate.Description = dbHotelBookingExtensionTemplate.Description;
        dsHotelBookingExtensionTemplate.EffectiveFrom = dbHotelBookingExtensionTemplate.Effective_From;
        dsHotelBookingExtensionTemplate.EffectiveTo = dbHotelBookingExtensionTemplate.Effective_To;
        dsHotelBookingExtensionTemplate.SkipAdminFeePolicy = dbHotelBookingExtensionTemplate.Skip_Admin_Fee_Policy;
        dsHotelBookingExtensionTemplate.ExtensionNoticePeriod = dbHotelBookingExtensionTemplate.Extension_Notice_Period;
        dsHotelBookingExtensionTemplate.ExtensionNoticePeriodType = dbHotelBookingExtensionTemplate.Extension_Notice_Period_Type;
        dsHotelBookingExtensionTemplate.DefaultExtensionTerm = dbHotelBookingExtensionTemplate.Default_Extension_Term;
        dsHotelBookingExtensionTemplate.DefaultExtensionTermType = dbHotelBookingExtensionTemplate.Default_Extension_Term_Type;
        dsHotelBookingExtensionTemplate.CreateDateTime = dbHotelBookingExtensionTemplate.Create_DateTime;
        dsHotelBookingExtensionTemplate.UpdateDateTime = dbHotelBookingExtensionTemplate.Update_DateTime;

        if (dbHotelBookingExtensionTemplate.CreatedByUser != null)
        {
            dsHotelBookingExtensionTemplate.CreatedByUser = new RPMAdminUser();
            dsHotelBookingExtensionTemplate.CreatedByUser.UserAccountID = dbHotelBookingExtensionTemplate.CreatedByUser.ID;
            dsHotelBookingExtensionTemplate.CreatedByUser.FirstName = dbHotelBookingExtensionTemplate.CreatedByUser.Name_First;
            dsHotelBookingExtensionTemplate.CreatedByUser.LastName = dbHotelBookingExtensionTemplate.CreatedByUser.Name_Last;
        }

        if (dbHotelBookingExtensionTemplate.UpdatedByUser != null)
        {
            dsHotelBookingExtensionTemplate.UpdatedByUser = new RPMAdminUser();
            dsHotelBookingExtensionTemplate.UpdatedByUser.UserAccountID = dbHotelBookingExtensionTemplate.UpdatedByUser.ID;
            dsHotelBookingExtensionTemplate.UpdatedByUser.FirstName = dbHotelBookingExtensionTemplate.UpdatedByUser.Name_First;
            dsHotelBookingExtensionTemplate.UpdatedByUser.LastName = dbHotelBookingExtensionTemplate.UpdatedByUser.Name_Last;
        }

        return dsHotelBookingExtensionTemplate;
    }
}
